import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const cars = [
  // BMW
  {
    company: "BMW",
    model: "M4 Competition",
    year: 2024,
    price: 84100,
    mileage: 1200,
    color: "Isle of Man Green",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The BMW M4 Competition delivers 503 hp from its twin-turbo inline-6, paired with an 8-speed automatic. Track-tested precision meets daily luxury with adaptive M suspension and carbon fiber accents.",
    featured: true,
    images: ["/cars/bmw-m8.png"],
  },
  {
    company: "BMW",
    model: "iX M60",
    year: 2024,
    price: 111500,
    mileage: 3400,
    color: "Storm Bay",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The BMW iX M60 combines 610 hp dual-motor AWD with a 111.5 kWh battery delivering 288 miles of range. Air suspension, Bowers & Wilkins audio, and a curved display define this electric flagship.",
    featured: true,
    images: ["/cars/porsche-cayenne.png"],
  },
  {
    company: "BMW",
    model: "7 Series 760i",
    year: 2024,
    price: 113600,
    mileage: 5600,
    color: "Carbon Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    seats: 5,
    description: "The range-topping 760i xDrive features a 536 hp twin-turbo V8, Executive Lounge rear seating with reclining seats, and BMW Theater Screen with 31.3-inch 8K display.",
    featured: false,
    images: ["/cars/rolls-royce-ghost.png"],
  },
  // Mercedes-Benz
  {
    company: "Mercedes-Benz",
    model: "AMG GT 63 S",
    year: 2024,
    price: 176900,
    mileage: 2800,
    color: "Obsidian Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The AMG GT 63 S E Performance packs 831 hp from a hybrid V8 powertrain. Hand-built engine, active aerodynamics, and rear-axle steering make this the ultimate four-door supercar.",
    featured: true,
    images: ["/cars/mercedes-amg-gt.png"],
  },
  {
    company: "Mercedes-Benz",
    model: "EQS 580",
    year: 2024,
    price: 125950,
    mileage: 4100,
    color: "High-tech Silver",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    seats: 5,
    description: "The EQS 580 offers 536 hp, 350-mile range, and the optional MBUX Hyperscreen spanning 56 inches. Rear-wheel steering, Burmester 4D audio, and Level 3 autonomous driving capability.",
    featured: false,
    images: ["/cars/mclaren-720s.png"],
  },
  {
    company: "Mercedes-Benz",
    model: "GLE 580",
    year: 2023,
    price: 82500,
    mileage: 12000,
    color: "Selenite Grey",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 7,
    description: "The GLE 580 features a 489 hp twin-turbo V8 with EQ Boost mild-hybrid technology. AIRMATIC air suspension, MBUX with augmented reality navigation, and three-row seating for family luxury.",
    featured: false,
    images: ["/cars/porsche-cayenne.png"],
  },
  // Porsche
  {
    company: "Porsche",
    model: "Taycan Turbo S",
    year: 2024,
    price: 187400,
    mileage: 1800,
    color: "Frozen Blue",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    seats: 5,
    description: "The Taycan Turbo S delivers 750 hp with launch control, 0-60 in 2.4 seconds, and a 280-mile range. Porsche Active Suspension Management, carbon ceramic brakes, and 800V architecture.",
    featured: true,
    images: ["/cars/porsche-911-gt3.png"],
  },
  {
    company: "Porsche",
    model: "Cayenne Turbo GT",
    year: 2024,
    price: 196800,
    mileage: 3200,
    color: "Arctic Grey",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The fastest Cayenne ever with 631 hp twin-turbo V8, 0-60 in 3.1s. Sport Chrono Package, ceramic composite brakes, and rear-axle steering set lap records for SUVs.",
    featured: false,
    images: ["/cars/porsche-cayenne.png"],
  },
  // Tesla
  {
    company: "Tesla",
    model: "Model S Plaid",
    year: 2024,
    price: 89990,
    mileage: 5200,
    color: "Midnight Cherry Red",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    seats: 5,
    description: "The Model S Plaid produces 1,020 hp from tri-motor AWD, hitting 0-60 in 1.99 seconds. 396-mile range, yoke steering, 17-inch cinematic display, and track mode for the drag strip.",
    featured: true,
    images: ["/cars/ferrari-sf90.png"],
  },
  {
    company: "Tesla",
    model: "Model X Plaid",
    year: 2024,
    price: 94990,
    mileage: 7800,
    color: "Pearl White",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 6,
    description: "The Model X Plaid delivers 1,020 hp with falcon-wing doors, 348-mile range, and seating for up to 6. yoke steering, tri-motor torque vectoring, and tow capacity of 5,000 lbs.",
    featured: false,
    images: ["/cars/hyundai-ioniq-5.png"],
  },
  // Audi
  {
    company: "Audi",
    model: "RS e-tron GT",
    year: 2024,
    price: 147100,
    mileage: 2100,
    color: "Daytona Grey",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    seats: 4,
    description: "The RS e-tron GT produces 637 hp with two-speed rear transmission, 0-60 in 3.1s. Adaptive air suspension, carbon roof, and 236-mile range with 270 kW DC fast charging.",
    featured: true,
    images: ["/cars/audi-rs-e-tron-gt.png"],
  },
  {
    company: "Audi",
    model: "RS Q8",
    year: 2024,
    price: 124500,
    mileage: 6400,
    color: "Nardo Grey",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The RS Q8 packs 591 hp twin-turbo V8, 0-60 in 3.7s. Sport differential, predictive active suspension, and matrix LED headlights make this the fastest Audi SUV.",
    featured: false,
    images: ["/cars/mclaren-750s.png"],
  },
  // Lamborghini
  {
    company: "Lamborghini",
    model: "Huracan Tecnica",
    year: 2024,
    price: 238295,
    mileage: 800,
    color: "Verde Mantis",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The Huracan Tecnica features a 631 hp naturally aspirated V10, rear-wheel drive, and LDVI dynamic control. Aerodynamic body, titanium exhaust, and Corsa-tuned chassis for pure driving emotion.",
    featured: true,
    images: ["/cars/lamborghini-aventador.png"],
  },
  {
    company: "Lamborghini",
    model: "Urus Performante",
    year: 2024,
    price: 260676,
    mileage: 1500,
    color: "Giallo Auge",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The Urus Performante delivers 657 hp, 0-60 in 3.3s. Carbon fiber body kit, titanium exhaust, and rally-inspired design make this the fastest SUV around the Nurburgring.",
    featured: false,
    images: ["/cars/maserati-levante.png"],
  },
  // Ferrari
  {
    company: "Ferrari",
    model: "296 GTB",
    year: 2024,
    price: 322986,
    mileage: 1200,
    color: "Rosso Corsa",
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The 296 GTB combines a 654 hp V8 with a 164 hp electric motor for 819 hp total. Assetto Fiorano package, active aero, and 25-mile electric-only mode redefine the mid-engine supercar.",
    featured: true,
    images: ["/cars/ferrari-sf90.png"],
  },
  // McLaren
  {
    company: "McLaren",
    model: "750S",
    year: 2024,
    price: 324000,
    mileage: 900,
    color: "Papaya Spark",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The 750S produces 740 hp from a twin-turbo V8, weighing just 2,815 lbs. Proactive chassis control, dihedral doors, and carbon fiber monocoque for razor-sharp handling.",
    featured: false,
    images: ["/cars/mclaren-750s.png"],
  },
  // Aston Martin
  {
    company: "Aston Martin",
    model: "Vantage V8",
    year: 2024,
    price: 186000,
    mileage: 2400,
    color: "Sapphire Blue",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The new Vantage packs 656 hp twin-turbo V8, 0-60 in 3.4s. Electronic rear differential, carbon ceramic brakes, and a全新 interior with 10.25-inch infotainment redefine the sports car.",
    featured: false,
    images: ["/cars/aston-martin-db12.png"],
  },
  // Range Rover
  {
    company: "Land Rover",
    model: "Range Rover Sport SV",
    year: 2024,
    price: 181200,
    mileage: 3800,
    color: "Batumi Gold",
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The Sport SV delivers 626 hp from a twin-turbo V8 mild-hybrid, 0-60 in 3.6s. 6D Dynamics air suspension, carbon ceramic brakes, and SV Mode for track-focused performance.",
    featured: true,
    images: ["/cars/porsche-cayenne.png"],
  },
  // Toyota
  {
    company: "Toyota",
    model: "GR Supra 3.0",
    year: 2024,
    price: 58250,
    mileage: 4500,
    color: "Phantom",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The GR Supra 3.0 features a 382 hp turbocharged inline-6, 0-60 in 3.9s. Adaptive variable suspension, Torsen limited-slip differential, and a driver-focused cockpit.",
    featured: false,
    images: ["/cars/toyota-supra.png"],
  },
  // Honda
  {
    company: "Honda",
    model: "Civic Type R",
    year: 2024,
    price: 43990,
    mileage: 6200,
    color: "Championship White",
    fuelType: "Gasoline",
    transmission: "Manual",
    bodyType: "Sedan",
    seats: 5,
    description: "The Civic Type R produces 315 hp from a turbocharged inline-6, rev-matching 6-speed manual, and front-wheel drive with helical LSD. Triple-exit exhaust and track-tuned dampers.",
    featured: false,
    images: ["/cars/honda-civic-type-r.png"],
  },
  // Hyundai
  {
    company: "Hyundai",
    model: "IONIQ 5 N",
    year: 2024,
    price: 66100,
    mileage: 2800,
    color: "Performance Blue",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The IONIQ 5 N delivers 641 hp dual-motor AWD, N Grin Boost for 641 hp, and N e-Shift simulating an 8-speed DCT. Track-ready with N Battery Preconditioning and drift mode.",
    featured: true,
    images: ["/cars/hyundai-ioniq-5.png"],
  },
  // Rivian
  {
    company: "Rivian",
    model: "R1T Adventure",
    year: 2024,
    price: 78000,
    mileage: 8200,
    color: "Forest Edge",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The R1T Adventure offers quad-motor AWD with 835 hp, 14.9 inches of ground clearance, and a 400+ mile range. Camp Mode, air compressor, and gear tunnel for overlanding.",
    featured: false,
    images: ["/cars/rivian-r1t.png"],
  },
  // Porsche (additional)
  {
    company: "Porsche",
    model: "911 GT3 RS",
    year: 2024,
    price: 241100,
    mileage: 1500,
    color: "Racing Yellow",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The 911 GT3 RS features a 518 hp naturally aspirated flat-6, DRS active rear wing, and aero producing 904 lbs of downforce at 177 mph. Carbon fiber body and rear-axle steering.",
    featured: true,
    images: ["/cars/porsche-911-gt3.png"],
  },
  // Bugatti
  {
    company: "Bugatti",
    model: "Chiron Super Sport",
    year: 2024,
    price: 3900000,
    mileage: 500,
    color: "Jet Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The Chiron Super Sport produces 1,578 hp from an 8.0L quad-turbo W16, 0-60 in 2.3s, and a top speed of 273 mph. Titanium exhaust, custom aero, and hand-crafted luxury.",
    featured: true,
    images: ["/cars/bugatti-chiron.png"],
  },
  // Rolls-Royce
  {
    company: "Rolls-Royce",
    model: "Cullinan",
    year: 2024,
    price: 355000,
    mileage: 2200,
    color: "Black Diamond",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The Cullinan is Rolls-Royce's first SUV, featuring a 563 hp twin-turbo V12,Magic Carpet Ride air suspension, and coach doors. The pinnacle of luxury SUVs with hand-crafted interior.",
    featured: true,
    images: ["/cars/rolls-royce-ghost.png"],
  },
  {
    company: "Rolls-Royce",
    model: "Ghost",
    year: 2024,
    price: 330000,
    mileage: 3100,
    color: "Silver",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Sedan",
    seats: 5,
    description: "The Ghost features a 563 hp twin-turbo V12, Planar Suspension System, and Starlight Headliner with 1,344 fiber optic lights. Effortless elegance redefined.",
    featured: false,
    images: ["/cars/rolls-royce-ghost.png"],
  },
  // Bentley
  {
    company: "Bentley",
    model: "Bentayga",
    year: 2024,
    price: 245000,
    mileage: 4500,
    color: "Onyx Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The Bentayga combines 542 hp twin-turbo V8 performance with hand-crafted luxury. Diamond-knurled controls, Naim audio, and up to 7 seats for the ultimate luxury SUV.",
    featured: true,
    images: ["/cars/bentley-continental-gt.png"],
  },
  {
    company: "Bentley",
    model: "Continental GT",
    year: 2024,
    price: 245000,
    mileage: 3800,
    color: "Amethyst Grey",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The Continental GT features a 650 hp twin-turbo W8, rotating display, and diamond-in-diamond quilting. Grand touring perfection with 200+ mph capability.",
    featured: false,
    images: ["/cars/bentley-continental-gt.png"],
  },
  // Lamborghini
  {
    company: "Lamborghini",
    model: "Aventador SVJ",
    year: 2024,
    price: 517000,
    mileage: 1200,
    color: "White",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The Aventador SVJ produces 770 hp from a naturally aspirated V12, ALA 2.0 active aerodynamics, and rear-wheel steering. Nurburgring record holder for production cars.",
    featured: true,
    images: ["/cars/lamborghini-aventador.png"],
  },
  // Mercedes-Benz
  {
    company: "Mercedes-Benz",
    model: "G-Class AMG G63",
    year: 2024,
    price: 180000,
    mileage: 5200,
    color: "Obsidian Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The AMG G63 packs 577 hp twin-turbo V8, hand-built engine, three locking differentials, and iconic boxy design. Rugged luxury that conquers any terrain.",
    featured: true,
    images: ["/cars/mercedes-amg-gt.png"],
  },
  // Aston Martin
  {
    company: "Aston Martin",
    model: "DB12",
    year: 2024,
    price: 245000,
    mileage: 2800,
    color: "Sapphire Blue",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The DB12 features a 671 hp twin-turbo V8, the most powerful series-production Aston Martin ever. Ultra-luxurious interior with 10.25-inch infotainment.",
    featured: false,
    images: ["/cars/aston-martin-db12.png"],
  },
  // Ferrari
  {
    company: "Ferrari",
    model: "SF90 Stradale",
    year: 2024,
    price: 625000,
    mileage: 1800,
    color: "Rosso Corsa",
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The SF90 Stradale combines a 769 hp V8 with three electric motors for 986 hp total. Plug-in hybrid with 15-mile electric range and 0-60 in 2.5 seconds.",
    featured: true,
    images: ["/cars/ferrari-sf90.png"],
  },
  // McLaren
  {
    company: "McLaren",
    model: "720S",
    year: 2024,
    price: 315000,
    mileage: 2400,
    color: "Glacier White",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The 720S produces 710 hp from a twin-turbo V8, weighs 2,828 lbs, and hits 0-60 in 2.8 seconds. Dihedral doors, carbon fiber Monocage II, and Proactive Chassis Control.",
    featured: false,
    images: ["/cars/mclaren-720s.png"],
  },
  // Porsche
  {
    company: "Porsche",
    model: "911 Carrera S",
    year: 2024,
    price: 130000,
    mileage: 4200,
    color: "Guards Red",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The 911 Carrera S delivers 443 hp from a twin-turbo flat-6, PASM sport suspension, and rear-axle steering. The benchmark sports car refined to perfection.",
    featured: false,
    images: ["/cars/porsche-911-gt3.png"],
  },
  // BMW
  {
    company: "BMW",
    model: "M8 Competition",
    year: 2024,
    price: 130000,
    mileage: 3600,
    color: "Frozen Dark Grey",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The M8 Competition packs 617 hp twin-turbo V8, M xDrive AWD, and carbon fiber roof. Luxury grand tourer with track-capable performance.",
    featured: false,
    images: ["/cars/bmw-m8.png"],
  },
  // Audi
  {
    company: "Audi",
    model: "R8 V10 Performance",
    year: 2024,
    price: 208000,
    mileage: 2900,
    color: "Mythos Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 2,
    description: "The R8 V10 Performance produces 602 hp from a naturally aspirated 5.2L V10, quattro AWD, and magnetic ride suspension. The last of the naturally aspirated supercars.",
    featured: true,
    images: ["/cars/audi-rs-e-tron-gt.png"],
  },
  // Maserati
  {
    company: "Maserati",
    model: "GranTurismo Folgore",
    year: 2024,
    price: 210000,
    mileage: 1500,
    color: "Grigio Maratea",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The GranTurismo Folgore produces 751 hp from tri-motor AWD, 800V architecture, and Italian craftsmanship. The first all-electric Maserati with 250+ mile range.",
    featured: false,
    images: ["/cars/maserati-levante.png"],
  },
  // Maserati Levante
  {
    company: "Maserati",
    model: "Levante Trofeo",
    year: 2024,
    price: 190000,
    mileage: 3200,
    color: "Bianco Alpi",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The Levante Trofeo features a 580 hp twin-turbo V8, Q4 AWD, and skyhook suspension. Italian craftsmanship meets SUV practicality with hand-stitched leather interior.",
    featured: false,
    images: ["/cars/maserati-levante.png"],
  },
  // Lexus
  {
    company: "Lexus",
    model: "LC 500",
    year: 2024,
    price: 98000,
    mileage: 5800,
    color: "Ultra White",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The LC 500 features a 471 hp naturally aspirated 5.0L V8, 10-speed automatic, and hand-pleated door panels. Grand touring elegance meets Japanese precision.",
    featured: false,
    images: ["/cars/lexus-lc-500.png"],
  },
  // Range Rover
  {
    company: "Land Rover",
    model: "Range Rover Autobiography",
    year: 2024,
    price: 195000,
    mileage: 4800,
    color: "Constellation Grey",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 5,
    description: "The Range Rover Autobiography features a 523 hp twin-turbo V8, executive seating, and 48V mild-hybrid. The definitive luxury SUV with unrivaled off-road capability.",
    featured: false,
    images: ["/cars/porsche-cayenne.png"],
  },
  // Cadillac
  {
    company: "Cadillac",
    model: "Escalade V",
    year: 2024,
    price: 150000,
    mileage: 6200,
    color: "Black Raven",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 7,
    description: "The Escalade V packs 682 hp supercharged V8, Magnetic Ride Control, and AKG 36-speaker audio. America's ultimate luxury SUV with Super Cruise hands-free driving.",
    featured: false,
    images: ["/cars/maserati-levante.png"],
  },
  // Lincoln
  {
    company: "Lincoln",
    model: "Navigator Black Label",
    year: 2024,
    price: 110000,
    mileage: 7500,
    color: "Infinite Black",
    fuelType: "Gasoline",
    transmission: "Automatic",
    bodyType: "SUV",
    seats: 7,
    description: "The Navigator Black Label features a 440 hp twin-turbo V6, 30-way adjustable seats, and Revel Ultima 20-speaker audio. American luxury at its finest.",
    featured: false,
    images: ["/cars/rivian-r1t.png"],
  },
  // Lucid
  {
    company: "Lucid",
    model: "Air Grand Touring",
    year: 2024,
    price: 138000,
    mileage: 3200,
    color: "Zenith Red",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    seats: 5,
    description: "The Air Grand Touring produces 819 hp, 516-mile range (longest of any EV), and 0-60 in 3.0 seconds. The most aerodynamic production car with 900V architecture.",
    featured: true,
    images: ["/cars/mclaren-720s.png"],
  },
  // Koenigsegg
  {
    company: "Koenigsegg",
    model: "Gemera",
    year: 2024,
    price: 1700000,
    mileage: 500,
    color: "Sally",
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "Coupe",
    seats: 4,
    description: "The Gemera produces 1,700 hp from a 2.0L 3-cylinder turbo hybrid with two electric motors. The world's first mega-GT with four seats and Koenigsegg Direct Drive.",
    featured: true,
    images: ["/cars/bugatti-chiron.png"],
  },
];

async function main() {
  console.log("Seeding database...");

  for (const car of cars) {
    await prisma.car.upsert({
      where: {
        id: car.model.toLowerCase().replace(/\s+/g, "-"),
      },
      update: car,
      create: {
        id: car.model.toLowerCase().replace(/\s+/g, "-"),
        ...car,
      },
    });
    console.log(`Created: ${car.company} ${car.model}`);
  }

  console.log(`Seeded ${cars.length} cars`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
